var hierarchy =
[
    [ "tannic::function::Abs", "da/de6/structtannic_1_1function_1_1Abs.html", null ],
    [ "tannic::operation::Addition", "d9/da3/structtannic_1_1operation_1_1Addition.html", null ],
    [ "tannic::expression::Argmax", "dc/d3e/structtannic_1_1expression_1_1Argmax.html", null ],
    [ "tannic::expression::Argmean", "d8/d27/structtannic_1_1expression_1_1Argmean.html", null ],
    [ "tannic::expression::Argmin", "d7/d32/structtannic_1_1expression_1_1Argmin.html", null ],
    [ "tannic::expression::Argsum", "df/d20/structtannic_1_1expression_1_1Argsum.html", null ],
    [ "tannic::operation::Binary< Operation, Operand, Cooperand >", "d7/d6b/classtannic_1_1operation_1_1Binary.html", null ],
    [ "tannic::Buffer", "d4/d50/classtannic_1_1Buffer.html", null ],
    [ "tannic::Callback< H, D >", "d2/d24/classtannic_1_1Callback.html", null ],
    [ "tannic::expression::Cartesian", "d7/d1c/structtannic_1_1expression_1_1Cartesian.html", null ],
    [ "tannic::expression::Comparison< Criteria, First, Second >", "dc/dc3/classtannic_1_1expression_1_1Comparison.html", null ],
    [ "tannic::expression::Complexification< Coordinates, Sources >", "d3/d42/classtannic_1_1expression_1_1Complexification.html", null ],
    [ "tannic::expression::Complexification< Coordinates, Real, Imaginary >", "d1/d19/classtannic_1_1expression_1_1Complexification_3_01Coordinates_00_01Real_00_01Imaginary_01_4.html", null ],
    [ "tannic::expression::Complexification< Coordinates, Source >", "df/dd0/classtannic_1_1expression_1_1Complexification_3_01Coordinates_00_01Source_01_4.html", null ],
    [ "tannic::transformation::Composition", "d4/d53/structtannic_1_1transformation_1_1Composition.html", null ],
    [ "tannic::transformation::Concatenation", "dd/d77/structtannic_1_1transformation_1_1Concatenation.html", null ],
    [ "tannic::transformation::Convolution1D", "db/dd5/classtannic_1_1transformation_1_1Convolution1D.html", null ],
    [ "tannic::transformation::Convolution2D", "d7/d4c/classtannic_1_1transformation_1_1Convolution2D.html", null ],
    [ "tannic::function::Cos", "d1/dd6/structtannic_1_1function_1_1Cos.html", null ],
    [ "tannic::function::Cosh", "df/dc5/structtannic_1_1function_1_1Cosh.html", null ],
    [ "tannic::Device", "d3/d46/classtannic_1_1Device.html", null ],
    [ "tannic::Devices", "d9/dd4/classtannic_1_1Devices.html", null ],
    [ "tannic::expression::EQ", "d0/dd6/structtannic_1_1expression_1_1EQ.html", null ],
    [ "std::exception", null, [
      [ "tannic::Exception", "d9/d87/classtannic_1_1Exception.html", null ]
    ] ],
    [ "tannic::function::Exp", "dc/da3/structtannic_1_1function_1_1Exp.html", null ],
    [ "tannic::expression::Expansion< Source >", "d0/d10/classtannic_1_1expression_1_1Expansion.html", null ],
    [ "tannic::operation::Exponentiation", "db/d23/structtannic_1_1operation_1_1Exponentiation.html", null ],
    [ "tannic::expression::Flatten< Source >", "d1/dbe/classtannic_1_1expression_1_1Flatten.html", null ],
    [ "tannic::float16_t", "d5/d2c/structtannic_1_1float16__t.html", null ],
    [ "tannic::function::Function< Functor, Argument >", "db/d37/classtannic_1_1function_1_1Function.html", null ],
    [ "tannic::expression::GE", "d2/d2d/structtannic_1_1expression_1_1GE.html", null ],
    [ "tannic::expression::GT", "d3/d70/structtannic_1_1expression_1_1GT.html", null ],
    [ "tannic::Header", "d1/d69/structtannic_1_1Header.html", null ],
    [ "tannic::Host", "df/da7/classtannic_1_1Host.html", null ],
    [ "tannic::expression::LE", "d2/d6a/structtannic_1_1expression_1_1LE.html", null ],
    [ "tannic::function::Log", "d9/d67/structtannic_1_1function_1_1Log.html", null ],
    [ "tannic::expression::LT", "d9/d96/structtannic_1_1expression_1_1LT.html", null ],
    [ "tannic::Metadata< Object >", "d4/df4/structtannic_1_1Metadata.html", null ],
    [ "tannic::Metadata< Tensor >", "d4/d78/structtannic_1_1Metadata_3_01Tensor_01_4.html", null ],
    [ "tannic::operation::Multiplication", "d0/dcf/structtannic_1_1operation_1_1Multiplication.html", null ],
    [ "tannic::expression::NE", "db/dd6/structtannic_1_1expression_1_1NE.html", null ],
    [ "tannic::operation::Negation", "d6/deb/structtannic_1_1operation_1_1Negation.html", null ],
    [ "tannic::Node", "df/d85/structtannic_1_1Node.html", null ],
    [ "tannic::transformation::Outer", "de/d42/structtannic_1_1transformation_1_1Outer.html", null ],
    [ "tannic::expression::Permutation< Source, Indexes >", "d0/d42/classtannic_1_1expression_1_1Permutation.html", null ],
    [ "tannic::expression::Polar", "d3/dd3/structtannic_1_1expression_1_1Polar.html", null ],
    [ "tannic::indexing::Range", "de/dea/structtannic_1_1indexing_1_1Range.html", null ],
    [ "Realification", "d6/d98/classRealification.html", null ],
    [ "tannic::expression::Realification< Source >", "db/d96/classtannic_1_1expression_1_1Realification.html", null ],
    [ "tannic::expression::Reduction< Reducer, Operand >", "da/dc5/classtannic_1_1expression_1_1Reduction.html", null ],
    [ "tannic::transformation::Repack", "d8/d0a/structtannic_1_1transformation_1_1Repack.html", null ],
    [ "tannic::transformation::Repetition", "da/d5d/structtannic_1_1transformation_1_1Repetition.html", null ],
    [ "tannic::function::Rsqrt", "dc/db8/structtannic_1_1function_1_1Rsqrt.html", null ],
    [ "tannic::Shape", "db/da7/classtannic_1_1Shape.html", null ],
    [ "tannic::function::Sin", "d5/d31/structtannic_1_1function_1_1Sin.html", null ],
    [ "tannic::function::Sinh", "de/d64/structtannic_1_1function_1_1Sinh.html", null ],
    [ "tannic::expression::Slice< Source, Indexes >", "dd/d0f/classtannic_1_1expression_1_1Slice.html", null ],
    [ "tannic::function::Sqrt", "d7/df8/structtannic_1_1function_1_1Sqrt.html", null ],
    [ "tannic::expression::Squeeze< Source >", "d7/dca/classtannic_1_1expression_1_1Squeeze.html", null ],
    [ "tannic::Strides", "dc/deb/classtannic_1_1Strides.html", null ],
    [ "tannic::operation::Subtraction", "d6/de5/structtannic_1_1operation_1_1Subtraction.html", null ],
    [ "tannic::function::Tan", "d2/d15/structtannic_1_1function_1_1Tan.html", null ],
    [ "tannic::function::Tanh", "d6/d39/structtannic_1_1function_1_1Tanh.html", null ],
    [ "tannic::Tensor", "da/d93/classtannic_1_1Tensor.html", null ],
    [ "tannic::Trait< T >", "d1/d96/structtannic_1_1Trait.html", null ],
    [ "tannic::Trait< Argument >", "d1/d96/structtannic_1_1Trait.html", null ],
    [ "tannic::Trait< Cooperand >", "d1/d96/structtannic_1_1Trait.html", null ],
    [ "tannic::Trait< First >", "d1/d96/structtannic_1_1Trait.html", null ],
    [ "tannic::Trait< Imaginary >", "d1/d96/structtannic_1_1Trait.html", null ],
    [ "tannic::Trait< Operand >", "d1/d96/structtannic_1_1Trait.html", null ],
    [ "tannic::Trait< Real >", "d1/d96/structtannic_1_1Trait.html", null ],
    [ "tannic::Trait< Second >", "d1/d96/structtannic_1_1Trait.html", null ],
    [ "tannic::Trait< Source >", "d1/d96/structtannic_1_1Trait.html", null ],
    [ "tannic::transformation::Transformation< Operation, Operands >", "d9/d4d/classtannic_1_1transformation_1_1Transformation.html", null ],
    [ "tannic::expression::Transpose< Source >", "d0/dd9/classtannic_1_1expression_1_1Transpose.html", null ],
    [ "tannic::operation::Unary< Operation, Operand >", "d7/d26/classtannic_1_1operation_1_1Unary.html", null ],
    [ "tannic::expression::Unsqueeze< Source >", "dd/d7d/classtannic_1_1expression_1_1Unsqueeze.html", null ],
    [ "tannic::expression::View< Source >", "d2/d9f/classtannic_1_1expression_1_1View.html", null ]
];