name: Deploy Doxygen Docs

on:
  push:
    branches: [ main ]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen & Graphviz
        run: |
          sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen
        run: |
          doxygen Doxyfile

      - name: Move to /docs
        run: |
          rm -rf docs
          mkdir -p docs
          mv docs/html/* docs/
          touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs