name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
  
      - name: Create build directory (Windows)
        if: runner.os == 'Windows'
        run: New-Item -ItemType Directory -Force -Path build
        shell: powershell

      - name: Create build directory (Linux/macOS)
        if: runner.os != 'Windows'
        run: mkdir -p build
        shell: bash
 
      - name: Configure (Windows)
        if: runner.os == 'Windows'
        working-directory: build
        shell: powershell
        run: cmake $Env:GITHUB_WORKSPACE
        continue-on-error: true

      - name: Configure (Linux/macOS)
        if: runner.os != 'Windows'
        working-directory: build
        shell: bash
        run: cmake $GITHUB_WORKSPACE
        continue-on-error: true
 
      - name: Build (Windows)
        if: runner.os == 'Windows'
        working-directory: build
        shell: powershell
        run: cmake --build .
        continue-on-error: true

      - name: Build (Linux/macOS)
        if: runner.os != 'Windows'
        working-directory: build
        shell: bash
        run: cmake --build .
        continue-on-error: true
 
      - name: Test (Windows)
        if: runner.os == 'Windows'
        working-directory: build
        shell: powershell
        run: ctest . --build-config Debug --rerun-failed --output-on-failure
        continue-on-error: true

      - name: Test (Linux/macOS)
        if: runner.os != 'Windows'
        working-directory: build
        shell: bash
        run: ctest . --build-config Debug --rerun-failed --output-on-failure
        continue-on-error: true