name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Clean build directory
        run: rm -rf build

      - name: Create build directory
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Configure
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: cmake $GITHUB_WORKSPACE

      - name: Build
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: cmake --build .

      - name: Test
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: ctest . --build-config Debug --rerun-failed --output-on-failure